In [22]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [23]:
wine = load_wine()

X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.Series(wine.target)

In [24]:
Q1 = X.quantile(0.25)
Q3 = X.quantile(0.75)

IQR = Q3 - Q1

mask = ~((X < (Q1 - 1.5 * IQR)) | (X > (Q3 + 1.5 * IQR))).any(axis=1)

X = X[mask]
y = y[mask]

print("Outliers Removed")
print("New Shape:", X.shape)

Outliers Removed
New Shape: (161, 13)


In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print("Dataset Split")


Dataset Split


In [26]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
acc_list = []

for k in range(1, 21):

    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    pred = knn.predict(X_test)

    acc = accuracy_score(y_test, pred)

    acc_list.append(acc)

best_k = acc_list.index(max(acc_list)) + 1

print("Best K:", best_k)
print("Best Accuracy:", max(acc_list))

Best K: 5
Best Accuracy: 1.0


In [28]:
knn_final = KNeighborsClassifier(n_neighbors=best_k)

knn_final.fit(X_train, y_train)

y_pred = knn_final.predict(X_test)

In [29]:
results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

results["Status"] = np.where(
    results["Actual"] == results["Predicted"],
    "Correct",
    "Wrong"
)

print("\nSample Results:")
print(results.head(15))


print("\nFinal Accuracy:", accuracy_score(y_test, y_pred))


Sample Results:
    Actual  Predicted   Status
0        1          1  Correct
1        2          2  Correct
2        2          2  Correct
3        2          2  Correct
4        1          1  Correct
5        0          0  Correct
6        2          2  Correct
7        0          0  Correct
8        0          0  Correct
9        1          1  Correct
10       1          1  Correct
11       2          2  Correct
12       0          0  Correct
13       1          1  Correct
14       2          2  Correct

Final Accuracy: 1.0


In [31]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)


# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n")
print(cm)

Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        13

    accuracy                           1.00        49
   macro avg       1.00      1.00      1.00        49
weighted avg       1.00      1.00      1.00        49

Confusion Matrix:

[[18  0  0]
 [ 0 18  0]
 [ 0  0 13]]
